### ISSUE TITLE
`response` is never `None`

### ISSUE THREAD

**Issue by theavey** [google/python-temescal#1]
I am trying to get this to work with my sound bar, and I am getting a `JSONDecodeError`. I believe the response I am getting is blank, but it is attempted to be decoded. 
The [`response` as returned from `decrypt_packet`](https://github.com/google/python-temescal/blob/master/temescal/__init__.py#L118) will never [be `None`](https://github.com/google/python-temescal/blob/ebc83f93e5ab35b83a0443e8bb8af973c0c2c32a/temescal/__init__.py#L98), though it seems that it can be blank.

I don't have a good way to test this right now, but it might be sufficient to do:

    if response:
        self.callback(json.loads(response))

Thanks for this, and I hope I can get it working for me.

**Comment by dunaparty** [comment]
Already fixed, this issue should be closed.

**Comment by theavey** [comment]
possibly fixed by 14de6bcdc543cd92f30c787ddf1ad15da8327874
