### ISSUE TITLE
New equalizer setting

### ISSUE THREAD

**Issue by teldri** [google/python-temescal#2]
I´ve been playing around with this library and a "LG SL10YG" soundbar.
Seems like LG added another equalizer setting, setting number 18. 
In the LG soundbar app it´s called "DTS:X" (not to confuse with "DTS Virtual:X" ...)

`equalisers = ["Standard", "Bass", "Flat", "Boost", "Treble and Bass", "User",
              "Music", "Cinema", "Night", "News", "Voice", "ia_sound",
              "Adaptive Sound Control", "Movie", "Bass Blast", "Dolby Atmos",
              "DTS Virtual X", "Bass Boost Plus"]`

should be extended to something like that:

`equalisers = ["Standard", "Bass", "Flat", "Boost", "Treble and Bass", "User",
              "Music", "Cinema", "Night", "News", "Voice", "ia_sound",
              "Adaptive Sound Control", "Movie", "Bass Blast", "Dolby Atmos",
              "DTS Virtual X", "Bass Boost Plus", "DTS X"]`

Would have made a quick pull request but reading and creating that CLA whatever something stopped me.

Would be nice to see that new equalizer setting implemented.

**Comment by mjg59** [comment]
Merged in #3 , thanks!
